package com.banking.system.controller;

import com.banking.system.dto.request.DepositRequest;
import com.banking.system.dto.request.TransferRequest;
import com.banking.system.dto.request.WithdrawRequest;
import com.banking.system.dto.response.ApiResponse;
import com.banking.system.dto.response.TransactionResponse;
import com.banking.system.service.RetryableTransactionService;
import com.banking.system.service.TransactionService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

/**
 * REST controller for financial transaction operations.
 *
 * IDEMPOTENCY KEY REQUIREMENT:
 * All mutation endpoints (POST) require an Idempotency-Key header.
 * This header must be a unique string (usually a UUID) generated by the client
 * for each new transaction. If the client retries with the same key,
 * the server returns the cached response without re-processing.
 *
 * Example header: Idempotency-Key: 550e8400-e29b-41d4-a716-446655440000
 */
@RestController
@RequestMapping("/api/v1/transactions")
@RequiredArgsConstructor
@Slf4j
public class TransactionController {

    private final RetryableTransactionService retryableTransactionService;
    private final TransactionService transactionService;

    /**
     * POST /api/v1/transactions/deposit
     *
     * Deposits money into an account.
     * Requires Idempotency-Key header.
     */
    @PostMapping("/deposit")
    public ResponseEntity<ApiResponse<TransactionResponse>> deposit(
            @Valid @RequestBody DepositRequest request,
            @RequestHeader("Idempotency-Key") String idempotencyKey) {

        log.info("REST | Deposit request | Account: {} | Amount: {} | Key: {}",
                request.getAccountId(), request.getAmount(), idempotencyKey);

        TransactionResponse response = retryableTransactionService.deposit(request, idempotencyKey);

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Deposit completed successfully", response));
    }

    /**
     * POST /api/v1/transactions/withdraw
     *
     * Withdraws money from an account.
     * Requires Idempotency-Key header.
     */
    @PostMapping("/withdraw")
    public ResponseEntity<ApiResponse<TransactionResponse>> withdraw(
            @Valid @RequestBody WithdrawRequest request,
            @RequestHeader("Idempotency-Key") String idempotencyKey) {

        log.info("REST | Withdraw request | Account: {} | Amount: {} | Key: {}",
                request.getAccountId(), request.getAmount(), idempotencyKey);

        TransactionResponse response = retryableTransactionService.withdraw(request, idempotencyKey);

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Withdrawal completed successfully", response));
    }

    /**
     * POST /api/v1/transactions/transfer
     *
     * Transfers money from one account to another.
     * Requires Idempotency-Key header.
     */
    @PostMapping("/transfer")
    public ResponseEntity<ApiResponse<TransactionResponse>> transfer(
            @Valid @RequestBody TransferRequest request,
            @RequestHeader("Idempotency-Key") String idempotencyKey) {

        log.info("REST | Transfer request | From: {} | To: {} | Amount: {} | Key: {}",
                request.getSourceAccountId(), request.getTargetAccountId(),
                request.getAmount(), idempotencyKey);

        TransactionResponse response = retryableTransactionService.transfer(request, idempotencyKey);

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Transfer completed successfully", response));
    }

    /**
     * GET /api/v1/transactions/account/{accountId}
     *
     * Retrieves paginated transaction history for an account.
     * Supports pagination via 'page' and 'size' query parameters.
     * Results are sorted by creation time (newest first).
     *
     * Example: GET /api/v1/transactions/account/{id}?page=0&size=10
     */
    @GetMapping("/account/{accountId}")
    public ResponseEntity<ApiResponse<Page<TransactionResponse>>> getTransactionHistory(
            @PathVariable UUID accountId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {

        log.debug("REST | Transaction history | Account: {} | Page: {} | Size: {}", accountId, page, size);

        Pageable pageable = PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt"));
        Page<TransactionResponse> history = transactionService.getTransactionHistory(accountId, pageable);

        return ResponseEntity.ok(ApiResponse.success("Transaction history retrieved", history));
    }
}
